swagger: "2.0"
info:
  description: This is the swagger file that goes with server code
  version: "1.0.0"
  title: Swagger REST API for Gerdau test
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /task:
    get:
      operationId: "task.read"
      tags:
        - "task"
      summary: "The task data structure supported by the server application"
      description: "Read the list of tasks"
      responses:
        200:
          description: "Successful read task list operation"
          schema:
            type: "array"
            items:
              properties:
                task_id:
                  type: "string"
                tname:
                  type: "string"
                tgroup:
                  type: "string"
                tdate:
                  type: "string"
                done_flag:
                  type: "string"
                timestamp:
                  type: "string"
    post:
      operationId: "task.create"
      tags:
        - "task"
      summary: "Create a new task and add it to the to do list"
      description: "Create a new task and add it to the to do list"
      parameters:
        - name: task
          in: body
          description: "Task to create"
          required: True
          schema:
            type: object
            properties:
              task_id:
                type: "string"
              tname:
                  type: "string"
              tgroup:
                type: "string"
              tdate:
                type: "string"
              done_flag:
                type: "string"
              timestamp:
                type: "string"
                description: Creation/Update timestamp
      responses:
        201:
          description: "Successfully created in list"

  /task/{task_id}:
    get:
      operationId: "task.read_a_task"
      tags:
        - "task"
      summary: "The task data structure supported by the server application"
      description: "Read the list of tasks"
      parameters:
        - name: task_id
          in: path
          description: unique identifier of a task
          type: string
          required: True
      responses:
        200:
            description: "Successful read task list operation"
            schema:
                properties:
                  tname:
                    type: "string"
                  tgroup:
                    type: "string"
                  tdate:
                    type: "string"
                  done_flag:
                    type: "string"
                  timestamp:
                    type: "string"
                    description: Creation/Update timestamp
                    
    put:
      operationId: task.update
      tags:
        - "task"
      summary: "Update the status of a task in the tasks list"
      description: "Update a task status in the tasks list"
      parameters:
        - name: task_id
          in: path
          description: task to update status
          type: string
          required: True
        - name: task
          in: body
          description: updated status
          schema:
            type: object
            properties:
              # tname:
              #   type: "string"
              # tgroup:
              #   type: "string"
              # tdate:
              #   type: "string"
              done_flag:
                type: "string"
              # timestamp:
              #   type: "string"
              timestamp:
                type: "string"
                description: Creation/Update timestamp
      responses:
        200:
          description: "Successfully updated task status in tasks list"

    delete:
      operationId: task.delete
      tags:
        - task
      summary: Delete a task from the tasks list
      description: Delete a task
      parameters:
        - name: task_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a task from tasks list

