swagger: "2.0"
info:
  description: This is the swagger file that goes with server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /task:
    get:
      operationId: "task.read"
      tags:
        - "task"
      summary: "The task data structure supported by the server application"
      description: "Read the list of tasks"
      responses:
        200:
          description: "Successful read task list operation"
          schema:
            type: "array"
            items:
              properties:
                tname:
                  type: "string"
                tgroup:
                  type: "string"
                tdate:
                  type: "string"
                timestamp:
                  type: "string"
